version: '3.7'

services:
  localstack:
    image: localstack/localstack-full:latest
    container_name: localstack_demo
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes: 
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: node-localstack
    expose: 
      - '8000'
    ports:
      - '8000:8000'
    command: npm run dev